[package]
name = "my_binary_project"
version = "0.1.0"
edition = "2024"


[lib]
name = "runtime"
path = "src/lib.rs"

[dependencies]
crossbeam = "0.8.4"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
